-- # How many distinct terms are in the sequence generated by a^(b) for 2 <= a  <= 100 and 2 <= b  <= 100?
import           Data.List                      ( nub )


countTerms :: Integer -> Integer -> Int
countTerms limitA limitB =
  length $ nub [ i ^ j | i <- [2 .. limitA], j <- [2 .. limitB] ]

main :: IO ()
main = do
  print $ countTerms 100 100
