# How many distinct terms are in the sequence generated by a^(b) for 2 <= a  <= 100 and 2 <= b  <= 100?


def count_terms(limit_a, limit_b):
    terms = set()
    for i in range(2, limit_a + 1):
        for j in range(2, limit_b + 1):
            terms.add(i ** j)
    return len(terms)


if __name__ == "__main__":
    print(count_terms(limit_a=100, limit_b=100))
